### PR TITLE
fix float errors with listThreads

### LINKED ISSUE #22: Minor bug: Float returned by listThreads
In line 208:
listThreads = args.maxthreads / 3

can return a float value which causes an error

For example:

INFO: Starting 66.66666666666666 delete threads...

Modify listThreads to force an integer value and it will work:
listThreads = int(args.maxthreads / 3)

### PR DESCRIPTION
**Pull request by geekpete**
Fixes https://github.com/eschwim/s3wipe/issues/22

### CODE REVIEW

**Comment by geekpete** [comment]
Is this one still relevant?

**Comment by calebmarchent** [comment]
@geekpete I would say "yes"; though when I hit the problem today; I resolved it with:

```python
listThreads = args.maxthreads // 3
```

**Comment by geekpete** [comment]
TIL, that's much neater.

**Review by davem-git — APPROVED** [review]

**Comment by geekpete** [comment]
Let me know if there's anything that needs addressing with this one.

**Comment by ferschubert-hm** [comment]
Issue is still present, fix in PR worked for me. Could it be merged to master? Thanks! And great script!

**Comment by geekpete** [comment]
I might close this one out, this project appears to be largely abandoned. This can be revived by whoever wants to PR it again.

**Pull request closed without merging**
